# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DH_HW_Animations' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit'

  target 'DH_HW_AnimationsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DH_HW_AnimationsUITests' do
    # Pods for testing
  end

end
